---
- name: Install package without dependencies of OS
  hosts: "{{ myhost }}"
  tasks:
    - name: Install "{{ mypkg }}"
      package:
        name: "{{ mypkg }}"
        state: latest
      check_mode: "{{ mode }}"
